### ISSUE TITLE
Bad address checksum

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/FastBTC#75]
1|FastBtcV3  | 2021-04-26T21:53:26: [2021-04-26T21:53:26.676Z] tx deposit handling met an error: Error: bad address checksum (argument="address", value="0x7587a0eA5822B81bcCC9e43876a050BB4037F709", code=INVALID_ARGUMENT, version=address/5.1.0) (argument="receiver", value="0x7587a0eA5822B81bcCC9e43876a050BB4037F709", code=INVALID_ARGUMENT, version=abi/5.0.7)
1|FastBtcV3  | 2021-04-26T21:53:26:     at Logger.makeError (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/logger/lib/index.js:180:21)
1|FastBtcV3  | 2021-04-26T21:53:26:     at Logger.throwError (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/logger/lib/index.js:189:20)
1|FastBtcV3  | 2021-04-26T21:53:26:     at Logger.throwArgumentError (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/logger/lib/index.js:192:21)
1|FastBtcV3  | 2021-04-26T21:53:26:     at AddressCoder.Coder._throwError (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:40:16)
1|FastBtcV3  | 2021-04-26T21:53:26:     at AddressCoder.encode (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/abi/lib/coders/address.js:29:18)
1|FastBtcV3  | 2021-04-26T21:53:26:     at /home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
1|FastBtcV3  | 2021-04-26T21:53:26:     at Array.forEach (<anonymous>)
1|FastBtcV3  | 2021-04-26T21:53:26:     at Object.pack (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
1|FastBtcV3  | 2021-04-26T21:53:26:     at TupleCoder.encode (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
1|FastBtcV3  | 2021-04-26T21:53:26:     at AbiCoder.encode (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
1|FastBtcV3  | 2021-04-26T21:53:26:     at ABICoder.encodeParameters (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/web3-eth-abi/lib/index.js:121:27)
1|FastBtcV3  | 2021-04-26T21:53:26:     at ABICoder.encodeFunctionCall (/home/ubuntu/FastBtcV3_2/FastBTC/node_modules/web3-eth-abi/lib/index.js:263:63)
1|FastBtcV3  | 2021-04-26T21:53:26:     at RskCtrl.transferFromMultisigWithWallet (/home/ubuntu/FastBtcV3_2/FastBTC/controller/rskCtrl.js:95:40)
1|FastBtcV3  | 2021-04-26T21:53:26:     at RskCtrl.transferFromMultisig (/home/ubuntu/FastBtcV3_2/FastBTC/controller/rskCtrl.js:174:31)
1|FastBtcV3  | 2021-04-26T21:53:26:     at runMicrotasks (<anonymous>)
1|FastBtcV3  | 2021-04-26T21:53:26:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
1|FastBtcV3  | 2021-04-26T21:53:26:   reason: 'bad address checksum (argument="address", value="0x7587a0eA5822B81bcCC9e43876a050BB4037F709", code=INVALID_ARGUMENT, version=address/5.1.0)',
1|FastBtcV3  | 2021-04-26T21:53:26:   code: 'INVALID_ARGUMENT',
1|FastBtcV3  | 2021-04-26T21:53:26:   argument: 'receiver',
1|FastBtcV3  | 2021-04-26T21:53:26:   value: '0x7587a0eA5822B81bcCC9e43876a050BB4037F709'
1|FastBtcV3  | 2021-04-26T21:53:26: }
1|F

**Comment by jamiemadrox779** [comment]
Duplicate
